// Generated by ts-to-zod
import { z } from "zod";

export const entitySchema = z.object({
    id: z.string()
});

export const userOwnedSchema = z.object({
    userId: z.string()
});

export const createdSchema = z.object({
    createdAt: z.string()
});

export const updatedSchema = z.object({
    updatedAt: z.string()
});

export const nursingFieldSchema = z.literal("ADULT");

export const programmeTypeSchema = z.union([z.literal("BSC_3YR"), z.literal("MSC_2YR"), z.literal("APPRENTICE"), z.literal("OTHER")]);

export const shiftTypeSchema = z.union([z.literal("EARLY"), z.literal("LATE"), z.literal("NIGHT"), z.literal("LONG_DAY"), z.literal("OTHER")]);

export const hoursEntryModeSchema = z.union([z.literal("NET"), z.literal("RAW")]);

export const shiftStatusSchema = z.union([z.literal("PLANNED"), z.literal("COMPLETED")]);

export const userSchema = entitySchema.extend(createdSchema.shape).extend(updatedSchema.shape).extend({
    displayName: z.string(),
    email: z.string().optional(),
    field: nursingFieldSchema,
    programmeType: programmeTypeSchema,
    currentPart: z.number(),
    totalParts: z.number(),
    startDate: z.string().optional(),
    targetRegistrationDate: z.string().optional()
});

export const placementSchema = entitySchema.extend(userOwnedSchema.shape).extend(createdSchema.shape).extend({
    name: z.string(),
    settingType: z.string().optional(),
    startDate: z.string().optional(),
    endDate: z.string().optional()
});

export const shiftSchema = entitySchema.extend(userOwnedSchema.shape).extend(createdSchema.shape).extend(updatedSchema.shape).extend({
    placementId: z.string().optional(),
    date: z.string(),
    startAt: z.string().optional(),
    endAt: z.string().optional(),
    shiftType: shiftTypeSchema,
    entryMode: hoursEntryModeSchema,
    rawDurationMins: z.number().optional(),
    breakMins: z.number().optional(),
    netHours: z.number(),
    isSimulated: z.boolean(),
    status: shiftStatusSchema,
    supervisingRnName: z.string().optional(),
    notes: z.string().optional()
});

export const shiftDraftSchema = shiftSchema.omit({ "id": true, "userId": true, "createdAt": true, "updatedAt": true });

export const logItemSchema = entitySchema.extend(userOwnedSchema.shape).extend(createdSchema.shape).extend({
    entityType: z.string(),
    entityId: z.string(),
    entityLabel: z.string().optional(),
    action: z.string(),
    summary: z.string(),
    batchId: z.string().optional()
});

export const logInputSchema = logItemSchema.omit({ "id": true, "createdAt": true });

export const annexeSchema = z.union([z.literal("NONE"), z.literal("A"), z.literal("B")]);

export const proficiencyStatusSchema = z.union([z.literal("NOT_YET_ACHIEVED"), z.literal("DEVELOPING"), z.literal("ACHIEVED")]);

export const evidenceTypeSchema = z.union([z.literal("REFLECTION"), z.literal("SKILL"), z.literal("SHIFT"), z.literal("MED_LOG")]);

export const proficiencySchema = entitySchema.extend({
    platform: z.number(),
    platformTitle: z.string(),
    annexe: annexeSchema,
    code: z.string(),
    statement: z.string(),
    orderIndex: z.number()
});

export const proficiencyProgressSchema = entitySchema.extend(userOwnedSchema.shape).extend(updatedSchema.shape).extend({
    proficiencyId: z.string(),
    status: proficiencyStatusSchema,
    targetPart: z.number().optional()
});

export const proficiencyStatusEventSchema = entitySchema.extend(createdSchema.shape).extend({
    progressId: z.string(),
    status: proficiencyStatusSchema,
    partIndex: z.number(),
    assessorName: z.string().optional(),
    note: z.string().optional(),
    occurredAt: z.string()
});

export const evidenceLinkSchema = entitySchema.extend(userOwnedSchema.shape).extend(createdSchema.shape).extend({
    proficiencyId: z.string(),
    evidenceType: evidenceTypeSchema,
    evidenceId: z.string()
});

export const evidenceLinkDraftSchema = evidenceLinkSchema.omit({ "id": true, "userId": true, "createdAt": true });

export const proficiencyStatusChangeSchema = z.object({
    status: proficiencyStatusSchema,
    partIndex: z.number(),
    occurredAt: z.string(),
    assessorName: z.string().optional(),
    note: z.string().optional()
});

export const medLogTypeSchema = z.union([z.literal("OBSERVED"), z.literal("ADMINISTERED")]);

export const calcTypeSchema = z.union([z.literal("TABLET_DOSE"), z.literal("LIQUID_DOSE"), z.literal("IV_RATE"), z.literal("WEIGHT_BASED"), z.literal("INFUSION_DROPS"), z.literal("UNIT_CONVERSION")]);

export const medicationSchema = entitySchema.extend(userOwnedSchema.shape).extend(createdSchema.shape).extend(updatedSchema.shape).extend({
    name: z.string(),
    brandNames: z.string().optional(),
    drugClass: z.string().optional(),
    bodySystem: z.string().optional(),
    routes: z.string().optional(),
    mechanismOfAction: z.string().optional(),
    sideEffects: z.string().optional(),
    monitoring: z.string().optional(),
    keyNotes: z.string().optional(),
    highAlert: z.boolean().optional()
});

export const medicationConditionSchema = entitySchema.extend({
    medicationId: z.string(),
    condition: z.string(),
    addedAt: z.string()
});

export const medicationLogSchema = entitySchema.extend(userOwnedSchema.shape).extend(createdSchema.shape).extend({
    medicationId: z.string().optional(),
    shiftId: z.string().optional(),
    type: medLogTypeSchema,
    date: z.string(),
    route: z.string().optional(),
    notes: z.string().optional()
});

export const calcDrillSchema = entitySchema.extend(userOwnedSchema.shape).extend(createdSchema.shape).extend({
    medicationId: z.string().optional(),
    calcType: calcTypeSchema,
    prompt: z.string(),
    answer: z.string(),
    lastAttempted: z.string().optional(),
    lastCorrect: z.boolean().optional()
});

export const calcStatSchema = entitySchema.extend(userOwnedSchema.shape).extend({
    calcType: calcTypeSchema,
    attempts: z.number(),
    correct: z.number(),
    lastAttempted: z.string()
});

export const medicationDraftSchema = medicationSchema.omit({ "id": true, "userId": true, "createdAt": true, "updatedAt": true });

export const medicationLogDraftSchema = medicationLogSchema.omit({ "id": true, "userId": true, "createdAt": true });

export const calcDrillDraftSchema = calcDrillSchema.omit({ "id": true, "userId": true, "createdAt": true });

export const skillSourceSchema = z.union([z.literal("ANNEXE_B"), z.literal("CUSTOM")]);

export const skillStageSchema = z.union([z.literal("OBSERVED"), z.literal("ASSISTED"), z.literal("PERFORMED_UNDER_SUPERVISION")]);

export const skillSchema = entitySchema.extend({
    userId: z.string().nullable(),
    name: z.string(),
    category: z.string(),
    source: skillSourceSchema,
    orderIndex: z.number()
});

export const skillProgressSchema = entitySchema.extend(userOwnedSchema.shape).extend(updatedSchema.shape).extend({
    skillId: z.string(),
    stage: skillStageSchema,
    signedOff: z.boolean(),
    signOffByName: z.string().optional(),
    signOffLocation: z.string().optional(),
    signOffDate: z.string().optional(),
    evidenceNote: z.string().optional(),
    shiftId: z.string().optional()
});

export const skillDraftSchema = skillSchema.omit({ "id": true });

export const skillSignOffSchema = skillProgressSchema.pick({ "signOffByName": true, "signOffLocation": true, "signOffDate": true, "evidenceNote": true, "shiftId": true });

export const reflectionModelSchema = z.literal("GIBBS");

export const gibbsStageSchema = z.union([z.literal("DESCRIPTION"), z.literal("FEELINGS"), z.literal("EVALUATION"), z.literal("ANALYSIS"), z.literal("CONCLUSION"), z.literal("ACTION_PLAN")]);

export const reflectionSchema = entitySchema.extend(userOwnedSchema.shape).extend(createdSchema.shape).extend(updatedSchema.shape).extend({
    title: z.string(),
    model: reflectionModelSchema,
    occurredOn: z.string().optional(),
    shiftId: z.string().optional(),
    isLocked: z.boolean(),
    piiAcknowledged: z.boolean()
});

export const reflectionSectionSchema = entitySchema.extend({
    reflectionId: z.string(),
    stage: gibbsStageSchema,
    content: z.string()
});

export const tagSchema = entitySchema.extend(userOwnedSchema.shape).extend({
    label: z.string()
});

export const reflectionTagSchema = entitySchema.extend({
    reflectionId: z.string(),
    tagId: z.string()
});

export const reflectionDraftSchema = reflectionSchema.omit({ "id": true, "userId": true, "createdAt": true, "updatedAt": true });

export const reflectionSectionInputSchema = z.object({
    stage: gibbsStageSchema,
    content: z.string()
});

export const revisionTargetTypeSchema = z.union([z.literal("EXAM"), z.literal("ASSIGNMENT"), z.literal("OSCE")]);

export const revisionMethodSchema = z.union([z.literal("SPACED_REPETITION"), z.literal("FIXED_BLOCK"), z.literal("POMODORO")]);

export const subjectSchema = entitySchema.extend({
    userId: z.string().nullable(),
    name: z.string()
});

export const revisionTargetSchema = entitySchema.extend(userOwnedSchema.shape).extend(createdSchema.shape).extend({
    type: revisionTargetTypeSchema,
    title: z.string(),
    date: z.string(),
    subjectId: z.string().optional()
});

export const revisionTopicSchema = entitySchema.extend(userOwnedSchema.shape).extend(createdSchema.shape).extend({
    subjectId: z.string(),
    title: z.string(),
    confidence: z.number(),
    lastReviewed: z.string().optional(),
    nextDue: z.string().optional()
});

export const revisionSessionSchema = entitySchema.extend(userOwnedSchema.shape).extend(createdSchema.shape).extend({
    topicId: z.string().optional(),
    method: revisionMethodSchema,
    scheduledStart: z.string(),
    scheduledEnd: z.string(),
    completed: z.boolean(),
    pomodoroCount: z.number().optional(),
    confidenceAfter: z.number().optional()
});

export const subjectDraftSchema = subjectSchema.omit({ "id": true });

export const revisionTargetDraftSchema = revisionTargetSchema.omit({ "id": true, "userId": true, "createdAt": true });

export const revisionTopicDraftSchema = revisionTopicSchema.omit({ "id": true, "userId": true, "createdAt": true });

export const revisionSessionDraftSchema = revisionSessionSchema.omit({ "id": true, "userId": true, "createdAt": true });

export const selfCareCheckinSchema = entitySchema.extend(userOwnedSchema.shape).extend(createdSchema.shape).extend({
    date: z.string(),
    shiftId: z.string().optional(),
    energy: z.number().optional(),
    note: z.string().optional(),
    items: z.string()
});

export const selfCareCheckinDraftSchema = selfCareCheckinSchema.omit({ "id": true, "userId": true, "createdAt": true });

export const breakRuleSchema = entitySchema.extend({
    userId: z.string().nullable(),
    minShiftMins: z.number(),
    maxShiftMins: z.number(),
    breakMins: z.number(),
    orderIndex: z.number()
});
